config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'habits#index'
  resources :habits, except: [:show, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/habit.rb
class Habit < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  belongs_to :user

  def mark_done
    self.done_today = true
    self.hot_streak += 1
    self.hot_record +=1 if self.hot_streak > self.hot_record
    self.previous_cold_streak = cold_streak
    self.cold_streak = 0
    self.previous_date_last_done = date_last_done
    self.date_last_done = Date.today
  end

  def unmark_done
    self.done_today = false
    self.hot_record -=1 if self.hot_streak == self.hot_record
    self.hot_streak -= 1
    self.cold_streak = self.previous_cold_streak
    self.date_last_done = self.previous_date_last_done
  end

  def last_done
    if self.date_last_done.nil?
      last_done = 'Never'
    else
      days_ago = (Date.today - date_last_done).to_i
      case days_ago
      when 0 then last_done = "Today"
      when 1 then last_done = "Yesterday"
      else
        last_done = "#{days_ago} days ago"
      end
    end
    last_done
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :habits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_habit, only: %i[ edit update destroy ]

  # GET /habits or /habits.json
  def index
    if params[:sort_by]
      @habits = sort_habits
    else
      @habits = Habit.all.order(created_at: :desc)
    end
    @habit = Habit.new
    @sorted_by = params[:sort_by]
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits or /habits.json
  def create
    @habit = current_user.habits.build(habit_params)

    if @habit.save
      redirect_to habit_url(@habit), notice: "#{@habit.name} was successfully created."
    else
      if @habit.errors.any?
        @habit.errors.each do |error|
          flash[:alert] = error.full_message
        end
      end
      render partial: "habits/new", locals: { habit: @habit }, status: :unprocessable_entity
    end
\
  end

  # PATCH/PUT /habits/1 or /habits/1.json
  def update
    respond_to do |format|
      sort_by = params[:habit].delete(:sort_by)
      if @habit.update(habit_params)
        @habit.done_today ? @habit.mark_done : @habit.unmark_done
        @habit.save!
        redirect_to habits_path(sorted_by: sort_by), notice: "#{@habit.name} was successfully updated."
      else
        if @habit.errors.any?
          @habit.errors.each do |error|
            flash[:alert] = error.full_message
          end
        end
        render :index, status: :unprocessable_entity
      end
    end
  end

  # DELETE /habits/1 or /habits/1.json
  def destroy
    @habit.destroy
    redirect_to habits_url, notice: "#{@habit.name} was deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_habit
    @habit = Habit.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def habit_params
    params.fetch(:habit, {}).permit(:name, :done_today, :hot_streak, :hot_record, :cold_streak, :date_last_done, :sort_by)
  end

  def sort_habits
    case params[:sort_by]
    when "created" then @habits = Habit.all.order(created_at: :desc)
    when "streak" then @habits = Habit.all.order(Arel.sql('CASE WHEN hot_streak > 0 THEN hot_streak ELSE 0 END DESC, cold_streak ASC'))
    when "record" then @habits = Habit.all.order(hot_record: :desc)
    when "done" then @habits = Habit.all.order(Arel.sql('CASE WHEN date_last_done IS NULL THEN 1 ELSE 0 END, date_last_done DESC'))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/habits/_edit.html.erb
<div data-edit-name-target="form" class="w-full hidden p-4 border border-secondary rounded-sm">
  <%= form_with(model: habit, class: "w-full mr-2 flex") do |f| %>
    <%= f.text_field :name, class: "w-full block rounded-sm border border-secondary outline-none" %>
    <%= f.submit 'Update', class: "ml-4 rounded-sm py-2 px-5 bg-secondary text-white inline-block font-medium cursor-pointer " %>
  <% end %>
</div>

app/views/habits/_new.html.erb
<div data-toggle-new-target="form" class="mt-4 mb-4 p-4 w-full bg-primary hidden rounded-sm border border-secondary">
  <%= form_with(model: habit, class: "w-full") do |f| %>
    <div class="flex justify-center">
      <%= f.text_field :name, class: "w-full block shadow rounded-sm border border-secondary outline-none" %>
      <%= f.submit 'Add', class: "ml-4 rounded-sm py-2 px-5 bg-secondary text-white inline-block font-medium cursor-pointer " %>
    </div>
  <% end %>
</div>

app/views/habits/_show.html.erb
<div class="flex w-full mb-4 items-center">
  <%= button_to habit_path(habit), data: { turbo_method: :delete, "toggle-edit-target" => "delete"  }, class: 'hidden mr-2 flex items-center text-secondary hover:text-secondary-600' do %>
    <i class="fa fa-trash"></i>
  <% end %>
  <%= link_to habit_path(habit, habit: { done_today: !habit.done_today?, sort_by: @sorted_by }), data: { turbo_method: :patch, "edit-name-target" => "name" }, class: 'flex-grow' do %>
    <div id="<%= dom_id habit %>" class="min-w-fit py-2 px-4 flex items-center border rounded-sm <%= habit.done_today ? "border-accent-700 bg-accent-100" : "bg-primary border-secondary-500" %>">
      <div class="w-16 shrink-0 text-start <%= habit.done_today ? "text-accent-700" : "text-secondary" %> font-semibold">
        <p>
          <% if habit.hot_streak > habit.cold_streak %>
            <%= "🔥 #{habit.hot_streak}" %>
          <% else %>
            <%= "🚫 #{habit.cold_streak}" %>
          <% end %>
        </p>
        <p>🏆 <%= habit.hot_record %></p>
      </div>
      <h2 class="grow shrink text-pretty text-left text-2xl <%= habit.done_today ? "text-accent-700" : "text-secondary" %>"><%= habit.name %></h2>
      <p class="ml-2 grow-0 text-end italic text-sm font-light <%= habit.done_today ? "text-accent-700" : "text-secondary" %>"><%= habit.last_done %></p>
    </div>
  <% end %>
  <%= render "habits/edit", habit: habit %>
  <button data-toggle-edit-target="edit" data-edit-name-target="pencil" data-action="click->edit-name#edit" class="hidden ml-2 flex items-center cursor-pointer text-secondary hover:text-secondary-600">
    <i class="fa fa-pencil"></i>
  </button>
</div>

app/views/habits/index.html.erb
<h2 class="my-4 text-center text-accent italic text-3xl">Get it done!</h2>
<h1 class="my-4 text-4xl font-black text-center text-secondary">Your Daily Habits</h1>
<div data-controller="sort-order" class="mb-4 flex items-center justify-between">
  <div class="flex">
    <%= form_tag habits_path, method: :get, class: "" do %>
      <%= label_tag :sort_by, "Sort:", class: "whitespace-nowrap mr-2 font-medium text-secondary" %>
      <% select_options = [
            ['Date Created', 'created'],
            ['Streak Length', 'streak'],
            ['Record Length', 'record'],
            ['Last Completed', 'done']
          ] %>
      <%= select_tag :sort_by, options_for_select(select_options, @sorted_by), class: "border border-secondary text-secondary text-sm rounded-sm focus:ring-accent", onchange: 'this.form.submit()' %>
    <% end %>
    <button class="ml-2 cursor-pointer text-secondary hover:text-secondary-600" data-sort-order-target="icon" data-action="click->sort-order#reverse">
      <i class="fa fa-sort"></i>
    </button>
  </div>
  <div>
    <button
            class="py-2 px-4 rounded-sm bg-secondary text-white font-medium self-center hover:bg-secondary-600"
            data-toggle-edit-target="button"
            data-action="click->toggle-edit#toggle">
      <i class="fa fa-eye"></i> Show options
    </button>
    <button
            class="py-2 px-4 rounded-sm bg-secondary text-white font-medium self-center hover:bg-secondary-600"
            data-toggle-new-target="button"
            data-action="click->toggle-new#toggle">
      <i class="fa fa-plus"></i> New Habit
    </button>
  </div>
</div>
<%= render "shared/flashes" %>
<%= render "habits/new", habit: @habit %>
<div class="mx-auto" data-controller="edit-name">
  <% @habits.each do |habit| %>
    <%= render "habits/show", habit: habit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsOnTrack</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-primary">
    <%= render "shared/navbar" %>
    <main class="mx-1 sm:mx-auto max-w-screen-sm " data-controller="toggle-edit toggle-new close-flash">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div id="notice" data-close-flash-target="flash" class="mb-4 mt-4 py-2 px-3 flex w-full justify-between items-center bg-green-50 text-green-500 font-medium rounded-lg">
    <%= notice %>
    <button type="button" data-close-flash-target="button" data-action="click->close-flash#close" class="py-1 px-4 rounded-2xl bg-green-200 hover:bg-green-300 focus:outline-none focus:ring focus:ring-green-400" aria-label="Close">
      <i class="fa fa-close"></i>
    </button>
  </div>
<% end %>
<% if alert %>
  <div id="alert" data-close-flash-target="flash" class="mb-4 mt-4 py-2 px-4 flex w-full justify-between items-center bg-alert-200 text-alert-500 font-medium rounded-sm border border-alert-500">
    <%= alert %>
    <button type="button" data-close-flash-target="button" data-action="click->close-flash#close" class="ml-2 py-1 px-4 rounded-sm text-alert-200 bg-alert-500 hover:bg-alert-400 focus:outline-none focus:ring focus:ring-alert-300" aria-label="Close">
      <i class="fa fa-close"></i>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="p-4 w-full flex justify-between content-center bg-secondary text-white">
  <p class="ml-2 text-lg">Welcome <%= current_user.email %></p>
  <div class="mr-2 cursor-pointer text-2xl">
    <i class="fa fa-lightbulb-o"></i>
    <i class="fa fa-sign-out"></i>
  </div>
</div>